baseURL: https://gordinmitya.ru/
languageCode: en-us
title: Dmitriy Gordin

theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  DateFormat: "January 2, 2006"
  defaultTheme: light # auto, dark, light
  disableThemeToggle: true

  ShowWordCount: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowCodeCopyButtons: false

  homeInfoParams:
    Title: "Hey,"
    Content: >
      I'm a software engineer with 9 years of experience in industry and Master degree in CS.
      Over the past 5 years specializing in image processing using C++, OpenCV, and OpenGL for efficient real-time applications.
      I have hands-on experience in training, optimizing, and deploying neural networks from PyTorch to Android and iOS apps.


      **Reach me out on:**

  socialIcons:
    - name: telegram
      url: "https://t.me/gordinmitya"
    - name: twitter
      url: "https://twitter.com/gordinmitya"
    - name: github
      url: "https://github.com/gordinmitya"

# menu:
#   main:
#     - identifier: about
#       name: About
#       url: /about/
#       weight: 10