baseURL: https://gordinmitya.ru/
languageCode: en-us
title: Dmitry Gordin

theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

params:
  DateFormat: "January 2, 2006"
  defaultTheme: light # auto, dark, light
  disableThemeToggle: true

  ShowWordCount: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowCodeCopyButtons: false

  homeInfoParams:
    Title: "Hey,"
    Content: >
      I’m a software engineer with 9 years of industry experience and a Master’s degree in Computer Science. 
      For the past 5 years, I have specialized in image processing using C++, OpenCV, and OpenGL for efficient real-time applications. 
      I have hands-on experience in training, optimizing, and deploying neural networks from PyTorch to Android and iOS apps.


      **Find me on:**

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/gordinmitya/"
    - name: twitter
      url: "https://twitter.com/gordinmitya"
    - name: github
      url: "https://github.com/gordinmitya"
    - name: telegram
      url: "https://t.me/gordinmitya"

# menu:
#   main:
#     - identifier: about
#       name: About
#       url: /about/
#       weight: 10
